name: Docker Publish

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  NAME: helioschat/sync

jobs:
  build:
    name: Publish image to Package repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.NAME }}:latest